mindmap
  root((Vast.ai Host Ansible Role))
    Architecture
      Install_Modes
        local
        native
        remote
      Platforms
        Debian
        Ubuntu
      Script_Run_Modes
        daemon
        standalone
    Context
      Codename
        Kaalia
    Ecosystem
      CI_CD
        GitHub_Actions
        Molecule
      Dependencies
        Ansible
        Docker
        Python
