---
- name: Converge remote standalone mode
  hosts: all
  gather_facts: true
  vars:
    vastai_host_account_identity: ''
    vastai_host_install_location: https://console.vast.ai/install
    vastai_host_install_mode: remote
    vastai_host_install_script_run_mode: standalone
    vastai_host_install_validate_certs: false
  tasks:
    - name: Include main role
      ansible.builtin.include_role:
        name: cogni-ai.vastai_host
