---
- name: Prepare hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Python for Ansible
      ansible.builtin.raw: |
        if command -v python3 || command -v python; then
          exit 0
        elif command -v apk; then
          apk add --no-cache python3 py3-pip
        elif command -v apt; then
          apt -y update && apt install -y python3-minimal
        elif command -v dnf; then
          dnf install -y python3
        elif command -v zypper; then
          zypper --non-interactive install python3
        else
          echo "No supported package manager found" >&2
          exit 1
        fi
      check_mode: false
      changed_when: false
