---
- name: Deploy install_update.sh
  ansible.builtin.include_tasks: _deploy_script.yml
  vars:
    native_script_source: install_update.sh
    native_script_dest: /var/lib/vastai_kaalia/install_update.sh
