---
- name: Deploy send_mach_info.py
  ansible.builtin.include_tasks: _deploy_script.yml
  vars:
    native_script_source: send_mach_info.py
    native_script_dest: /var/lib/vastai_kaalia/send_mach_info.py
