---
- name: Deploy start_self_test.sh
  ansible.builtin.include_tasks: _deploy_script.yml
  vars:
    native_script_source: start_self_test.sh
    native_script_dest: /var/lib/vastai_kaalia/start_self_test.sh
